// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTeatro.Context;

namespace ProyectoTeatro.Migrations
{
    [DbContext(typeof(TeatroDbContext))]
    [Migration("20220617153745_vfdsavf")]
    partial class vfdsavf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoTeatro.Models.Butaca", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("EstaLibre")
                        .HasColumnType("bit");

                    b.Property<int>("NroButaca")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Butacas");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.ButacaReserva", b =>
                {
                    b.Property<int>("IdButacaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdButaca")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.HasKey("IdButacaReserva");

                    b.ToTable("ButacaReserva");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NroButaca")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int?>("Teatroid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Teatroid");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Teatroid")
                        .HasColumnType("int");

                    b.HasKey("IdObra");

                    b.HasIndex("Teatroid");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaObra")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Sala", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Teatro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SalaPrincipalid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SalaPrincipalid");

                    b.ToTable("Teatro");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Teatroid")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Teatroid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Entrada", b =>
                {
                    b.HasOne("ProyectoTeatro.Models.Teatro", null)
                        .WithMany("Entradas")
                        .HasForeignKey("Teatroid");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Obra", b =>
                {
                    b.HasOne("ProyectoTeatro.Models.Teatro", null)
                        .WithMany("Obras")
                        .HasForeignKey("Teatroid");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Teatro", b =>
                {
                    b.HasOne("ProyectoTeatro.Models.Sala", "SalaPrincipal")
                        .WithMany()
                        .HasForeignKey("SalaPrincipalid");
                });

            modelBuilder.Entity("ProyectoTeatro.Models.Usuario", b =>
                {
                    b.HasOne("ProyectoTeatro.Models.Teatro", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("Teatroid");
                });
#pragma warning restore 612, 618
        }
    }
}
